### ISSUE TITLE
Distribute as a CLI.

### ISSUE THREAD

**Issue by BrianCraig** [werainkhatri/issue#3]
### Describe the bug

For using this package i had to:
 - Clone the repository
 - run `dart pub get` on root folder.
 - run `dart ./example/issue.dart` on root

### Expected usage

 - Installing global locally as a tool.
 - Run from any location (preferably using a cwd file as the configuration file, example default-issue.json)

###### This issue was created using [issue](https://pub.dev/packages/issue).

**Comment by werainkhatri** [comment]
well, at this stage, this is not to run as a standalone CLI but rather to integrate with another CLI (like [flutterfire_cli](https://github.com/invertase/flutterfire_cli/issues/6), from where the idea came from). I have a few future plans like the one you mention, but currently i have a few shorter term goals (mentioned in #1) which i'm focusing on.

thanks for pointing it out and being interested in it!
(and using `issue` to create these issues :p)
